server:
  port : 9999
zuul:
  routes:
    offer:
      path: /offer/**
      url: http://18.236.94.23:1001/api/v1
    shoe:
      path: /shoe/**
      url: http://18.236.94.23:1002/api/v1
    wishlist:
      path: /wishlist/**
      url: http://18.236.94.23:1003
    cart:
      path: /cart/**
      url: http://18.236.94.23:1004/api/v1
